django/learning_log/learning_log/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.views.generic.base import TemplateView 
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    #url(r'^$', TemplateView.as_view(template_name='index.html')),
    #path(r'' , include('learning_logs.urls',namespace = 'learning_logs')),
    path(r'' , include(('learning_logs.urls','learning_logs'),namespace = 'learning_logs')),
    #path(r'^users/' , include('users.urls' , namespace = 'users')),
    path(r'users/' , include(('users.urls','users') , namespace = 'users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/learning_log/learning_logs/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$' , views.index , name = 'index'),
	url(r'^topics/$' , views.topics , name = 'topics'),
	url(r'^topics/(?P<topic_id>\d+)/$' , views.topic , name = 'topic'),
	url(r'^new_topic/$' , views.new_topic , name = 'new_topic'),
	url(r'^delete_topic/$' , views.delete_topic , name = 'delete_topic'),
	url(r'^new_entry/(?P<topic_id>\d+)/$' , views.new_entry , name = 'new_entry'),
	url(r'^detail/(?P<entry_id>\d+)/$', views.detail, name='detail'),
	url(r'^edit_entry/(?P<entry_id>\d+)/$' , views.edit_entry , name = 'edit_entry'),
	url(r'^upload/$', views.upload, name = 'upload')
]

django/learning_log/users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView

from . import views

urlpatterns = [
	#url(r'^login/$' , LoginView.as_view , {'template_name':'users/login.html'} , name = 'login'),
    url(r'^Login/$', views.Login,name='Login'),
	url(r'^logout/$' , views.logout_view , name = 'logout'),
	url(r'^register/$' , views.register , name = 'register'),
]

django/learning_log/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
	text = models.CharField(max_length = 200)
	date_added = models.DateTimeField(auto_now_add = True)
	owner = models.ForeignKey(User,on_delete=models.CASCADE)

	def __str__(self):
		return self.text

class Entry(models.Model):
	topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
	text = models.TextField()
	titles = models.CharField(max_length = 200)
	date_added = models.DateTimeField(auto_now_add = True)
	
	class Meta:
		verbose_name_plural = 'entries'
	def __str__(self):
		print('dddddd')
		return self.text[:150] + '...'

class IMG(models.Model):
	img = models.ImageField(upload_to='img')
	name = models.CharField(max_length=20)

django/learning_log/learning_logs/forms.py
from django import forms

from .models import Topic,Entry

class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields  = ['text']
		labels = {'text':''}
class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ['text']
		labels = {'text':''}
		widgets = {'text':forms.Textarea(attrs={'cols':80})}

django/learning_log/learning_logs/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from .models import Topic,Entry,IMG

from django.http import HttpResponseRedirect , Http404
from django.urls import reverse
from .forms import TopicForm,EntryForm
from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
def check_topic_owner(topic , request):
	if topic.owner != request.user:
		raise Http404

@csrf_exempt
def index(request):
	print("这是接收到的数据")
	print(request.POST)
	return render(request , 'learning_logs/index.html')
	# return JsonResponse({'code':'1','message':'11'})

@csrf_exempt
def topics(request):
	print("这是topics接收到的数据")
	print(request.user)
	topicsF = Topic.objects.filter(owner=request.user).order_by('date_added')
	topics = getTopics(topicsF)
	return JsonResponse({'code':'1','message':topics})

@login_required
def topic(request,topic_id):
	print("这是topic接收到的数据")
	topic = Topic.objects.get(id = topic_id)
	check_topic_owner(topic , request)
	entriesF = topic.entry_set.order_by('-date_added')
	entries = getEntries(entriesF)
	return JsonResponse({'code':'1','message':entries})

@login_required
def new_topic(request):
	print("这是new_topic接收到的数据")
	print(request.POST['text'])
	if request.method != 'POST':
		return JsonResponse({'code':'0','message':'请求错误'})
	else:
		obj = Topic.objects.create(text=request.POST['text'], owner=request.user)
		print(obj.id)
		if obj:
			return JsonResponse({'code':'1','message':'保存成功'})
		else:
			return JsonResponse({'code':'-1','message':'保存失败'})

def delete_topic(request):
	print("这是delete_topic接收到的数据")
	print(request.POST['id'])
	if request.method != 'POST':
		return JsonResponse({'code':'0','message':'请求错误'})
	else:
		topic = Topic.objects.get(id=request.POST['id'])
		print(topic.id)
		if topic:
			topic.delete()
			return JsonResponse({'code':'1','message':'保存成功'})
		else:
			return JsonResponse({'code':'-1','message':'保存失败'})
			
@login_required
def new_entry(request,topic_id):
	print("这是new_entry接收到的数据")
	topic = Topic.objects.get(id = topic_id)
	check_topic_owner(topic , request)
	if request.method != 'POST':
		return JsonResponse({'code':'0','message':'请求错误'})
	else:
		content = request.POST['content']
		title = request.POST['title']
		obj = Entry.objects.create(topic=topic, text=content, titles=title)
		if obj:
			print(obj.id)
			return JsonResponse({'code':'1','message':"保存成功"})
		else:
			return JsonResponse({'code':'-1','message':'保存失败'})

def detail(request, entry_id):
	print("这是detail接收到的数据")
	if request.method == 'POST':
		entry = Entry.objects.get(id = entry_id)
		if entry:
			print(entry.titles)
			date = entry.date_added.strftime('%Y-%m-%d %H:%M:%S')
			content = {'entry':entry.text, 'title': entry.titles, 'date':date}
			return JsonResponse({'code':'1','message':content})
	else:
		return JsonResponse({'code':'0','message':'请求错误'})

@login_required
def edit_entry(request , entry_id):
	entry = Entry.objects.get(id = entry_id)
	topic = entry.topic
	check_topic_owner(topic , request)
	if request.method != 'POST':
		form = EntryForm(instance = entry)
	else:
		form = EntryForm(instance = entry , data = request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('learning_logs:topic' , 
										args=[topic.id]))
	context = {'topic':topic , 'entry':entry , 'form':form}
	return render(request , 'learning_logs/edit_entry.html' , context)
		
def getTopics(Modeltopics):
	topics = []
	length = len(Modeltopics)
	for item in Modeltopics:
		topics.append({"id":item.id, "title": item.text})
	return topics

def getEntries(Modeltopics):
	entries = []
	for item in Modeltopics:
		data = item.date_added.strftime('%Y-%m-%d %H:%M:%S')
		entries.append({"id":item.id, "text": item.text, "title": item.titles, "data":data})
	return entries

def upload(request):
	print("这只upload接收到的数据")
	print(request)
	if request.method == 'POST':
		new_img = IMG(
			img=request.FILES.get('file'),
			name = request.FILES.get('file').name
		)
		obj = IMG.objects.create(img=request.FILES.get('file'), name=request.FILES.get('file').name)
		print(obj.img)
		imgUrl = 'media/' + str(obj.img)
	return JsonResponse({'code':'-1','message':'保存失败', 'imgUrl': imgUrl})
















	

django/learning_log/learning_logs/templates/learning_logs/base.html
<style>
 li {list-style-type:none;}
</style>

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width , initial-scale=1">
		
		<title>Learning Log</title>
		
		<link href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css" rel="stylesheet">
		<link href="/static/css/jumbotron-narrow.css" rel="stylesheet" rel="stylesheet">
	</head>
	
	<body>
		
		<!-- Static navbar -->
		<nav class="navbar navbar-default navbar-static-top">
			<div class="container">

				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed"
							 data-toggle="collapse" data-target="#navbar"
							 aria-expanded="false" aria-controls="navbar">
					</button>
					<a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
				</div>

				<div id="navbar" class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
						<li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
					</ul>
					
					<ul class="nav navbar-nav navbar-right">
						{% if user.is_authenticated %}
							<li><a>Hello,{{user.username}}.</a></li>
							<li><a href="{% url 'users:logout'%}">logout</a></li>
						{% else %}
							<li><a href="{% url 'users:register' %}">register</a></li>
							<li style="margin-left:10px"><a href="{% url 'users:login' %}">log in</a></li>
						{% endif %}
					</ul>
				</div><!--/.nav-collapse -->						 	
			</div>
		</nav>

		<div class="container">
			<div class="page-header">
				{% block header %}{% endblock header %}
			</div>
			<div>
				{% block content %}{% endblock content %}
			</div>
		</div>
	</body>
</html>

django/learning_log/learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}


{% block header %}
	<h2>
		<a href = "{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
	</h2>
{% endblock header %}

{% block content %}
	<h3>Edit entry:</h3>
	<form action = "{% url 'learning_logs:edit_entry' entry.id%}" method='post' class='form'>
		{% csrf_token %}
		{{ form.as_p }}

		
			<button name = "submit" class='btn btn-primary'>save change</button>
		
	</form>
{% endblock content %}

django/learning_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
	<div class='jumbotron'>
		<h1>Track your learning.</h1>
	</div>
{% endblock header %}

{% block content %}
	<h1> 
		<a href="{% url 'users:register' %}">Register an account</a> to make
		your own Learning Log,and list the topics you're learning about.
	</h2>
	<h2>
		whenever you lear something new about topic, make an entry summarizing
		what you're learned.
	</h2>
{% endblock content %}

django/learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}


{% block header %}
	<h2>
		<a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
	</h2>
{% endblock header %}
{% block content %}
	<h3>Add a new Entry:</h3>
	<form action="{% url 'learning_logs:new_entry' topic.id %}" method = 'post' class='form'>
		{% csrf_token %}
		{{ form.as_p }}

		
			<button name='submit' class='btn btn-primary'>add entry</button>
		
	</form>

{% endblock content %}

django/learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}


{% block header %}
	<h2>Add a new topoc:</h2>
{% endblock header %}
{% block content %}
	<form action="{% url 'learning_logs:new_topic' %}" method='post' class="form">
		{% csrf_token %}
		{{ form.as_p }}

		
			<button name='submit' class='btn btn-primary'>add topic</button>
		
		
	</form>
{% endblock content %}

django/learning_log/learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block header %}
	<h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
	<p>
		<a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
	</p>
		{% for entry in entries %}
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3>
						{{ entry.date_added|date:'M d, H:i'}}
						<small>
							<a href = "{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a>
						</small>
					</h3>
				</div>
				
				<div class="panel-body">
					{{ entry.text|linebreaks }}
				</div>
			</div>
		{% empty %}
			There are no entries for this topic yet.
		{% endfor %}
{% endblock content %}

django/learning_log/learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block header %}	
	<h1>Topics</h1>
{% endblock header %}

{% block content %}
<ul>
	{% for topic in topics%}
		<li>
			<h3><a href = "{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>
		</li>
	{% empty %}
		</li>EMPTY!!</li>
	{% endfor %}
</ul>
<h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a></h3>
{% endblock content%}

django/learning_log/learning_logs/templates/learning_logs/upload.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="img">
    <button type="submit">上传</button>
</form>